### ISSUE TITLE
Can only play Tampering cards

### ISSUE THREAD

**Issue by dAnjou** [dehydr8/elevation-of-privilege#31]
Hi,

we played a round of this game in our team today with everyone being remote which makes things less dynamic to begin with. We then found it quite odd that it lets us play only Tampering cards. I think it'd be nicer if you could play any card you deem most relevant for your particular system so that the game picks up speed and excitement from the beginning.

Besides that it's a pretty cool implementation of the game 👍

**Comment by dehydr8** [comment]
Hi Max,

Thank you for the feedback :)

It follows the same rules as the physical card game. The game is supposed to start from the 3 of Tampering, everyone plays a Tampering card until there is a winner, then the winner can choose to play another suit.

Are you suggesting we allow any card to be played by anyone?

**Comment by dAnjou** [comment]
Hey, thanks for the fast response!

> Are you suggesting we allow any card to be played by anyone?

Yup, and not even a full round of the same suit. With 6 players that becomes quite boring and time-consuming if the threats aren't too relevant.

**Comment by ChristophNiehoff** [comment]
Hi @dAnjou 
thank you for this idea. I agree that starting every game with Tampering is not a good option for repeated games. But I also agree with @dehydr8 that we should not drift away from the original card game too much. Adam Shostack created EoP as a serious _game_. And like in every game one has to comply with the rules, otherwise the EoP degrades to just a list of threats and looses a vital part of its game dynamics.

So, I created a patch that is compromise: When creating a game the start suit can be chosen. For repeated games the team can decide with which topic they would like to start.
