### ISSUE TITLE
Future of this repository

### ISSUE THREAD

**Issue by ChristophNiehoff** [dehydr8/elevation-of-privilege#52]
Dear @dehydr8 

Thank you very much for this app. It is really awesome.

As this repository has been stale for quite some time now, I would like to ask you, what your future plans for this app will be? Currently, we are actively developing patches to the EoP game (including e.g. fixes to the open issues). Are you still actively maintaining this repo, such that we can submit our patches as pull requests? Otherwise, we would fork this repo and move development to the new place.

What do you think?

**Comment by dehydr8** [comment]
Hi @ChristophNiehoff

Thank you for your interest.

It started as a personal project that we started using at Careem where I currently work, the interest faded due to the following reasons:

- For non-tech stakeholders, viewing the models and threats became a challenge as the produced artifact is a JSON file. We ended up creating a tool to parse the models, create relevant issues and produce a text report that got uploaded to our wiki.
- It became tedious for the engineers to keep their Threat Dragon models and identified threats up to date. They ended up creating markdown files with a textual threat model (similar to https://tools.ietf.org/html/rfc6819) and kept it in their repos.
- We added a few enhancements to Threat Dragon that we never really contributed back to the original repo, e.g. ability to add data elements to flows. This limited the features that we could add in the EoP game.
- We couldn't keep up with the project maintenance and improvements due to other pressing issues.

I personally would like to contribute more and add some requested features like #49 and #31 and multiple game modes with custom decks. If you already have patches that you can send as pull requests, that would be awesome. I'm also open to adding collaborators if it would make it easy.

Best regards,

**Comment by ChristophNiehoff** [comment]
In an offline conversation we came to the agreement to add @ChristophNiehoff as a collaborator to this repository. We hope to add a bunch of new features in the future.
